# This file is a part of PDDLRL project.
# Copyright (c) 2020 Clement Gehring (clement@gehring.io)
# Copyright (c) 2021 Masataro Asai (guicho2.71828@gmail.com, masataro.asai@ibm.com), IBM Corporation


name: pddlrl
dependencies:
  - python=3.8
  - parallel
  - curl
  - compilers
  - cmake
  - automake
  - libzlib
  - pip
  - pip:
      - tensorflow==2.3.*
      - tensorflow_probability==0.11.*
      - jax==0.2.9
      - https://storage.googleapis.com/jax-releases/cuda102/jaxlib-0.1.61+cuda102-cp38-none-manylinux2010_x86_64.whl
      - chex==0.0.3
      - dm-acme==0.2.0
      - dm-env==1.3
      - dm-haiku==0.0.3
      - gin-config==0.4.0
      - gym==0.18.0
      - optax==0.0.2
      - rlax==0.0.3
      - luigi
      - git+https://github.com/guicho271828/pddlenv.git
      - git+https://github.com/gehring/jax-nlm.git
      - -e .
